POST http://localhost:3000/register
Content-Type:application/json

{
  "username": "bcdam_richard",
  "name": "Adam Richard",
  "password": "lihageifdsuric",
  "gender": "male",
  "location": "Detroit"
}
###
POST http://localhost:3000/login
Content-Type:application/json

{
  "username": "am_richard",
  "password": "ichard_567"
}
###
PUT http://localhost:3000/change-password
Content-Type:application/json

{
  "username": "bcdam_richard",
  "oldPassword": "lihageifdsuric",
  "newPassword": "123"
}